package com.nihao.crm.mapper.activity.remark;

import com.nihao.crm.entityClass.activity.remark.ActivityRemark;

import java.util.List;
import java.util.Map;

public interface ActivityRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int insert(ActivityRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int insertSelective(ActivityRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    ActivityRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int updateByPrimaryKeySelective(ActivityRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int updateByPrimaryKey(ActivityRemark row);

    /**
     * 向数据库的t_activity_remark表中添加数据
     * @param activityRemark com.nihao.crm.entityClass.activity.remark.ActivityRemark
     */
    int createActivityRemark(ActivityRemark activityRemark);

    /**
     * 获取t_activity_remark表中的所有信息
     */
    List<ActivityRemark> getAllActivityRemark();

    /**
     * 通过活动id查询t_activity_remark表中的数据
     */
    List<ActivityRemark> byIdSelectActivityRemark(Map<String, String> map);

    /**
     * 通过活动id批量删除数据
     */
    int removeActivityRemark(String[] array);

    /**
     * 通过活动备注id, 删除活动备注
     */
    int deleteActivityRemark(String id);

    /**
     * 通过活动备注的id查询活动备注信息
     */
    String selectActivityRemark(String id);

    /**
     * 通过活动备注的id, 修改活动备注信息
     */
    int updateActivityRemark(ActivityRemark activityRemark);
}