package com.nihao.crm.mapper.clue.remark;

import com.nihao.crm.entityClass.clue.remark.ClueRemark;

import java.util.List;

public interface ClueRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int insert(ClueRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int insertSelective(ClueRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    ClueRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int updateByPrimaryKeySelective(ClueRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int updateByPrimaryKey(ClueRemark row);

    /**
     * 通过线索id, 查询所有线索备注信息
     */
    List<ClueRemark> byIdSelectClueRemark(String id);
}