package com.nihao.crm.mapper.user;

import com.nihao.crm.entityClass.user.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 04 10:51:14 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 04 10:51:14 CST 2022
     */
    int insert(User row);

    /**
     * 向数据库中添加用户信息
     */
    int insertAccountNumber(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 04 10:51:14 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 04 10:51:14 CST 2022
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Jun 04 10:51:14 CST 2022
     */
    int updateByPrimaryKey(User row);

    /**
     * 通过用户输入的账户名和密码查询数据
     */
    User selectByNameAndPassword(Map<String, String> map);

    /**
     * 通过用户的id修改密码
     * @param map Map集合, 存放password和id
     * @return int类型的数据
     */
    int byIdChangePassword(Map<String, String> map);

    /**
     * 通过用户的id查询用户信息
     * @param id id
     * @return User类型的数据
     */
    User byIdQueryData(String id);

    /**
     * 查询所有用户信息
     */
    List<User> selectAllUser();

    int insertAccount(User user);
}