package com.nihao.crm.mapper;

import com.nihao.crm.mapper.ActivityRemark;

public interface ActivityRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int insert(ActivityRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int insertSelective(ActivityRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    ActivityRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int updateByPrimaryKeySelective(ActivityRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_remark
     *
     * @mbg.generated Fri Jun 17 14:44:03 CST 2022
     */
    int updateByPrimaryKey(ActivityRemark row);
}