package com.nihao.crm.mapper;

import com.nihao.crm.mapper.ClueRemark;

public interface ClueRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int insert(ClueRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int insertSelective(ClueRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    ClueRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int updateByPrimaryKeySelective(ClueRemark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue_remark
     *
     * @mbg.generated Wed Jul 13 11:18:25 CST 2022
     */
    int updateByPrimaryKey(ClueRemark row);
}