package com.nihao.crm.mapper;

import com.nihao.crm.mapper.Clue;

public interface ClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue
     *
     * @mbg.generated Thu Jul 07 16:22:28 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue
     *
     * @mbg.generated Thu Jul 07 16:22:28 CST 2022
     */
    int insert(Clue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue
     *
     * @mbg.generated Thu Jul 07 16:22:28 CST 2022
     */
    int insertSelective(Clue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue
     *
     * @mbg.generated Thu Jul 07 16:22:28 CST 2022
     */
    Clue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue
     *
     * @mbg.generated Thu Jul 07 16:22:28 CST 2022
     */
    int updateByPrimaryKeySelective(Clue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clue
     *
     * @mbg.generated Thu Jul 07 16:22:28 CST 2022
     */
    int updateByPrimaryKey(Clue row);
}